###############################################################################
#
# Docker compose configuration for production
#
# Before running this compose file, ensure you ran the setup.ps1 or setup.sh
# to configure and download the required dependencies for this project.
#
###############################################################################

name: jippy-prod

services:
  #############################################################################
  # Databases and caches
  #############################################################################
  db:
    image: postgis/postgis:18-3.6
    restart: unless-stopped
    volumes:
      - ./.osm-data/db:/var/lib/postgresql
    environment:
      POSTGRES_USERNAME: ${DOCKER_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USERNAME -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 99999
      start_period: 30s
  cache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 9999
      start_period: 30s

  #############################################################################
  # maptiler/tileserver-gl
  # This service is for serving map tiles to the mobile app or on the server.
  #############################################################################
  tileserver:
    image: maptiler/tileserver-gl:latest
    restart: unless-stopped
    volumes:
      - ./.osm-data/tileserver:/data
      - ./scripts/tileserver/config.json:/data/config.json
    command:
      - "-c"
      - "/data/config.json"
      - "--public_url"
      - "${NEXT_PUBLIC_TILESERVER_URL}"
    healthcheck:
      test: [ "CMD-SHELL", "node /usr/src/app/src/healthcheck.js" ]
      interval: 30s
      timeout: 10s
      retries: 9999
    depends_on:
      db:
        condition: service_healthy

  #############################################################################
  # mediagis/nominatim for geocoding
  #############################################################################
  geocoder:
    image: mediagis/nominatim:5.3
    restart: unless-stopped
    volumes:
      - ./.osm-data/nominatim-persist:/var/lib/postgresql/16/main
      - ./.osm-data/nominatim:/nominatim/data
      - ./.osm-data/philippines-latest.osm.pbf:/nominatim/data/philippines-latest.osm.pbf
    environment:
      PBF_PATH: /nominatim/data/philippines-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/asia/philippines-updates/
      IMPORT_WIKIPEDIA: false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/search?q=jaro"]
      interval: 30s
      retries: 9999
      start_period: 20m
    depends_on:
      db:
        condition: service_healthy
    shm_size: 1G

  #############################################################################
  # OSRM or Open Source Routing Machine for driving & bicycle (motorcycles)
  #############################################################################
  driving_router:
    image: osrm/osrm-backend:latest
    restart: unless-stopped
    volumes:
      - ./.osm-data/osrm-driving:/data
    command:
      - "osrm-routed"
      - "--algorithm"
      - "mld"
      - "/data/philippines-latest.osrm"
  driving_bicycle:
    image: osrm/osrm-backend:latest
    restart: unless-stopped
    volumes:
      - ./.osm-data/osrm-bicycle:/data
    command:
      - "osrm-routed"
      - "--algorithm"
      - "mld"
      - "/data/philippines-latest.osrm"

  osrm_foot:
    image: osrm/osrm-backend:latest
    restart: unless-stopped
    volumes:
      - ./.osm-data/osrm-foot:/data
    command:
      - "osrm-routed"
      - "--algorithm"
      - "mld"
      - "/data/philippines-latest.osrm"

  #############################################################################
  # Algorithm
  #############################################################################
  algorithm:
    build:
      context: services/
      dockerfile: JippyServices.Algorithm/Dockerfile
    restart: unless-stopped
    environment:
      Services__Nominatim: http://geocoder:8080
      Services__OSRM__Driving: http://driving_router:5000
      Services__OSRM__Bicycle: http://driving_bicycle:5000
      Services__OSRM__Foot: http://osrm_foot:5000
      ConnectionStrings__DefaultConnection: ${DOTNET_POSTGRES_URL}
      ConnectionStrings__RedisCache: cache:6379
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      geocoder:
        condition: service_healthy
      driving_router:
        condition: service_started
      driving_bicycle:
        condition: service_started
      osrm_foot:
        condition: service_started

  #############################################################################
  # Main Application
  #############################################################################
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_FROM_ADDRESS: ${RESEND_FROM_ADDRESS}
      POSTGRES_URL: postgres://${DOCKER_POSTGRES_USERNAME}:${DOCKER_POSTGRES_PASSWORD}@db/${DOCKER_POSTGRES_DB_NAME}?schema=public
      REDIS_URL: redis://cache:6379
      NOMINATIM_URL: http://geocoder:8080
      OSRM_DRIVING_URL: http://driving_router:5000
      OSRM_BICYCLE_URL: http://driving_bicycle:5000
      OSRM_FOOT_URL: http://osrm_foot:5000
      ALGORITHM_URL: http://algorithm:8080
      NEXT_PUBLIC_TILESERVER_URL: ${NEXT_PUBLIC_TILESERVER_URL}
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      geocoder:
        condition: service_healthy
      driving_router:
        condition: service_started
      driving_bicycle:
        condition: service_started
      osrm_foot:
        condition: service_started

  #############################################################################
  # Cloudflare Proxy to expose in the public web
  #############################################################################
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run --token ${DOCKER_CLOUDFLARED_TOKEN}
    depends_on:
      tileserver:
        condition: service_healthy
      app:
        condition: service_started
