using System.Text.Json.Serialization;
using JippyServices.Algorithm.Navigator.V2;

namespace JippyServices.Algorithm.Contracts.V2.Responses;

/// <summary>
/// A single navigation instruction within a <see cref="RouteLeg"/>.
/// Walk legs receive turn-by-turn OSRM instructions; transit legs receive
/// board/alight/transfer instructions generated by <see cref="InstructionGenerator"/>.
/// </summary>
public sealed class Instruction
{
    /// <summary>Human-readable instruction text displayed to the user.</summary>
    [JsonPropertyName("text")]
    public required string Text { get; init; }

    /// <summary>The type of manoeuvre this instruction describes.</summary>
    [JsonPropertyName("maneuver_type")]
    public required ManeuverType ManeuverType { get; init; }
}

/// <summary>Classifies the type of navigation action an <see cref="Instruction"/> describes.</summary>
[JsonConverter(typeof(JsonStringEnumConverter<ManeuverType>))]
public enum ManeuverType
{
    /// <summary>The start of a walk or transit leg.</summary>
    [JsonStringEnumMemberName("depart")] Depart,

    /// <summary>A directional turn during a walk leg.</summary>
    [JsonStringEnumMemberName("turn")] Turn,

    /// <summary>Board a transit vehicle (jeepney or tricycle).</summary>
    [JsonStringEnumMemberName("board")] Board,

    /// <summary>Alight from the current transit vehicle.</summary>
    [JsonStringEnumMemberName("alight")] Alight,

    /// <summary>Transfer between two transit vehicles at an interchange point.</summary>
    [JsonStringEnumMemberName("transfer")] Transfer,

    /// <summary>The final destination has been reached.</summary>
    [JsonStringEnumMemberName("arrive")] Arrive,
}

