import path from "node:path";

import * as utils from "./utils.mjs";

const __dirname = import.meta.dirname;
const flags = new Set(process.argv.slice(2));

async function main() {
  if (flags.has("--use-own-deployments")) {
    console.log("Due to the nature of this project's requirements, this option is deprecated.");
    console.log("What you need to do is:");
    console.log("  1. Download Docker (Desktop or Engine) here:");
    console.log("     Desktop    : https://www.docker.com/products/docker-desktop/");
    console.log("     Engine only: https://docs.docker.com/engine/");
    console.log("  2. Install");
    console.log("  3. Run \"npm run setup\" without the need of any extra flags.");
    console.log("");
    console.log("There are no other extra things you need to do before this. Ports are now");
    console.log("auto-generated and it shouldn't conflict to any of your existing services.");

    process.exit(0);
  }

  // Token generation for authentication
  const token = utils.token.generatePassword(32, "!#%&()*+,/:;<=>?@[]^`{|}");
  utils.env.write("runtime.better.auth.secret", token);
  utils.env.write("runtime.better.auth.url", "http://localhost:3000");

  // Database configuration
  const databaseUsername = await utils.env.ask(
    "Your PostgreSQL username",
    "runtime.postgres.username",
    "postgres",
  );

  let databasePassword = utils.token.generatePassword(32);
  utils.env.write("runtime.postgres.password", databasePassword);

  const databaseName = await utils.env.ask(
    "Your PostgreSQL database name",
    "runtime.postgres.db",
    "jippy",
  );

  const databaseHost = await utils.env.ask(
    "Your PostgreSQL host",
    "runtime.postgres.host",
    "localhost",
  );

  let databasePort = await utils.env.ask(
    "Your PostgreSQL port (leave blank for autogenerated port)",
    "runtime.postgres.port",
  );
  if (utils.str.isEmpty(databasePort)) {
    databasePort = Math.floor(Math.random() * (65535 - 1024 + 1) + 1024).toString();
    utils.env.write("runtime.postgres.port", databasePort);
  }

  // Configure nominatim
  utils.env.write("runtime.next.public.nominatim.url", "http://localhost:6701");
  utils.env.write("runtime.next.public.valhalla.url", "http://localhost:6702");
  utils.env.write("runtime.next.public.tileserver.url", "http://localhost:6703");

  // Generate a connection string
  const dbConnectionOptions = {
    username: databaseUsername,
    password: databasePassword,
    host: databaseHost,
    port: databasePort,
    name: databaseName,
    query: { schema: "public" },
  };

  utils.env.write("runtime.postgres.url", utils.db.createConnectionString(dbConnectionOptions));

  // Nominatim DSN
  const nominatimDSN = `pgsql:dbname=nominatim;host=db;user=${databaseUsername};password=${databasePassword}`;
  utils.env.write("runtime.nominatim.database.dsn", nominatimDSN);

  // Write to root
  await utils.env.export(path.join(__dirname, "../.env"));

  // Download required files for any osm related applications
  console.log("Downloading required files for nominatim, valhalla and tileserver...");
  await utils.db.preDockerConfigure();

  console.log("Building...");
  console.log("Note: This will take from 30 minutes or more than 1 hour depending on your internet connection");
  console.log("      and hardware.");
  console.log("");

  // Run the tilemaker.
  console.log("  - Running tilemaker...");
  await utils.process.spawnAsync(
    "docker",
    [
      "run",
      "-it",
      "--rm",
      "-w", "/data",
      "-v", "./.osm-data/tileserver:/data",
      "-v", "./.osm-data/philippines-latest.osm.pbf:/data/philippines-latest.osm.pbf",
      "ghcr.io/systemed/tilemaker:master",
      "--input", "/data/philippines-latest.osm.pbf",
      "--output", "/data/map.mbtiles",
      "--process", "/data/process-openmaptiles.lua",
      "--config", "/data/config-openmaptiles.json",
    ], { cwd: path.join(__dirname, "../") },
  );

  // Run the docker-compose
  console.log("  - Running docker-compose...");
  await utils.process.spawnAsync(
    "docker",
    [
      "compose",
      "up", "-d", "--wait",
    ], { cwd: path.join(__dirname, "../") },
  );

  console.log("    Wait 5s...");
  await utils.timers.wait(5);

  console.log("  - Creating database...");
  await utils.db.setupDatabase(dbConnectionOptions);

  console.log("    Wait 5s...");
  await utils.timers.wait(5);

  console.log("  - Enabling PostGIS extension...");
  await utils.db.enablePostgisExtension(dbConnectionOptions);

  console.log("    Wait 5s...");
  await utils.timers.wait(5);

  console.log("  - Running migrations...");
  await utils.process.spawnAsync("npm", ["run", "db:migrate"], {
    cwd: path.join(__dirname, "../"),
  });

  console.log("");
  console.log("Successfully generated .env file!");
  console.log("You may run 'service:*' and 'db:*' scripts on npm without running the setup again.");
  console.log("");
  console.log("Here's a brief explainer of what those scripts do:");
  console.log("  service:up    - Builds and creates all services and networks for you");
  console.log("  service:down  - Removes all services and removes all networks");
  console.log("  service:start - Starts all services without needing to build them again.");
  console.log("                  (Implies you already service:up it before and you just stopped it)");
  console.log("  service:stop  - Stops all services without removing them.");
  console.log("  db:migrate    - Migrates the database schema to the latest version");
  console.log("  db:generate   - Generates a new migration file.");
  console.log("  db:push       - Pushes the database schema to the database");
  console.log("  db:studio     - Launches drizzle studio");
  console.log("");
  console.log("Happy coding!");
  console.log("");
}

main().catch(console.error);
